### ISSUE TITLE
I would like to know more about the refined data set you provided.

### ISSUE THREAD

**Issue by Rachel-hyy** [CAU-HE/CMCDNet#4]
Hello, author. I would like to inquire about the image numbers corresponding to the 18 regions in the dataset you provided. For example, in the test set, which ones are roi 4 and roi 17? I would like to know more about the refined data set you provided and look forward to hearing from you soon.

**Comment by CAU-HE** [comment]
Hello, researcher.
&nbsp; &nbsp;&nbsp;


Due to the large amount of data downloaded originally, it was not saved and only the file name can be provided. But the file name may be missing, for example, Sentinel 2 may have multiple scenes. You can download and supplement data based on these clues.


Alternatively, data can be obtained by directly searching for the corresponding time and location based on the specific description of ROI in the paper.
















fly
***@***.***



&nbsp;




-

**Comment by CAU-HE** [comment]
I have replied to the email I sent through Github. If you haven't received the email, you can leave your email here and I will send you your personal email.

**Comment by Rachel-hyy** [comment]
First of all, thank you for your reply. And then I want to ask you two more questions.

The first question is: On which platform was the dataset you used originally downloaded? Can you give us the web address?

The second question is: Is the optical image processed in the data set you give? It seems that they are not the most raw optical images, like a map with the irrelevant areas removed. Does this have any effect on training?

**Comment by CAU-HE** [comment]
I have replied to the email I sent through Github.

**Comment by Umi1227** [comment]
Hello,author.I also want to inquire about the image numbers corresponding to the 18 regions in the dataset.Thanks.
